name: beta

on:
  push:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  android:
    name: Build Beta APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo "$KEYSTORE_FILE"
      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Beta APK
        run: |
          ./gradlew assembleBeta --stacktrace \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=key0 \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Beta APK
        uses: actions/upload-artifact@v4
        with:
          name: beta-apk
          path: app/build/outputs/apk/beta/app-beta.apk

      - name: Create prerelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta-${{ github.run_id }}
          release_name: Beta ${{ github.run_id }}
          draft: false
          prerelease: true

      - name: Upload APK to prerelease
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/beta/app-beta.apk
          asset_name: app-beta.apk
          asset_content_type: application/vnd.android.package-archive
